# Generated by Django 2.0.1 on 2018-04-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csh',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
